### ISSUE TITLE
Uso de arrow functions

### ISSUE THREAD

**Issue by juanda99** [carlosazaustre/react-firebase-chat#2]
¿Por qué no usas arrow functions?
Te ahorrarías los constructores en lo que lo único que haces es el bind del this.

**Comment by carlosazaustre** [comment]
¿Te refieres dentro de los `render()`? No es una buena práctica poner ahí la función que se ejecute, porque cada vez que se llama al método render se crea una nueva función.

**Comment by juanda99** [comment]
Por ej en la class App:
```
class App extends Component {
  constructor () {
    super()
    // this.handleAuth = this.handleAuth.bind(this)
    // this.handleLogout = this.handleLogout.bind(this)
  }
```

Defines las funciones como:
```
 handleAuth => () {
    const provider = new firebase.auth.GoogleAuthProvider()
    provider.addScope('https://www.googleapis.com/auth/plus.login')

    firebase.auth().signInWithPopup(provider)
      .then(result => console.log(`${result.user.email} ha iniciado sesión`))
      .catch(error => console.log(`Error ${error.code}: ${error.message}`))
  }

  handleLogout => () {
    firebase.auth().signOut()
      .then(result => console.log('Te has desconectado correctamente'))
      .catch(error => console.log(`Error ${error.code}: ${error.message}`))
  }
```
Y así te ahorrarías crear el constructor entero.

**Comment by juanda99** [comment]
Acabo de ver que en la doc de Facebook está como lo has puesto.
Entiendo que es más didáctico así entonces...

**Comment by carlosazaustre** [comment]
Hola @juanda99 !
Bueno, así se podría hacer si no fuera una clase que extiende de React.Component, si fuera un componente representacional, pero si tiene funciones es más un componente funcional o 'smartcomponent' y es mejor que herede de React.Component.
